export const initialColumns = [
  { columnId: "no", columnName: "No", width: 37, resizable: false, visible: true },
  { columnId: "displayName", columnName: "DisplayName", width: 100, resizable: true, reorderable: true, visible: true },
  { columnId: "color", columnName: "Color", width: 50, resizable: true, reorderable: true, visible: true },
  { columnId: "plannedStartDate", columnName: "PlanS", width: 50, resizable: true, reorderable: true, visible: true },
  { columnId: "plannedEndDate", columnName: "PlanE", width: 50, resizable: true, reorderable: true, visible: true },
  { columnId: "plannedDays", columnName: "Days", width: 40, resizable: true, reorderable: true, visible: true },
  { columnId: "actualStartDate", columnName: "ActS", width: 50, resizable: true, reorderable: true, visible: true },
  { columnId: "actualEndDate", columnName: "ActE", width: 50, resizable: true, reorderable: true, visible: true },
  { columnId: "dependency", columnName: "Dep", width: 60, resizable: true, reorderable: true, visible: true },
  { columnId: "textColumn1", columnName: "Text1", width: 50, resizable: true, reorderable: true, visible: true },
  { columnId: "textColumn2", columnName: "Text2", width: 50, resizable: true, reorderable: true, visible: true },
  { columnId: "textColumn3", columnName: "Text3", width: 50, resizable: true, reorderable: true, visible: true },
  { columnId: "textColumn4", columnName: "Text4", width: 50, resizable: true, reorderable: true, visible: true },
  { columnId: "isIncludeHolidays", columnName: "IncHol", width: 50, resizable: true, reorderable: true, visible: true },
]